###########################################################################################
 # Pontificia Universidad Javeriana
 # Autor: David Santiago Calderon Idarraga
 # Fecha: 11/10/2025
 # Materia: Sistemas Operativos
 # Tema: Sistemas de FIcheros
 # Descripción: Automatizacion de compilacion de ficheros del laboratrio Sistema de Fichero
 ##########################################################################################
 
 
 # 'gcc' es el compilador estándar para programas en C.
GCC = gcc

PROGRAMAS = lab01 lab02
#Regla para compilar de forma automatica el laboratorio #1 y #2
lab01:
	$(GCC) modulo.c $@.c -o $@
lab0:
	$(GCC) modulo.c $@.c -o $@
# Regla para limpiar los ejecutables generados.
clean:
	$(RM) $(PROGRAMAS)

